# Generated by Django 5.2.13 on 2026-04-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='VehicleDetails',
        ),
    ]
