# Generated by Django 5.2.13 on 2026-04-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_vehicle_vehicledetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleDetails',
            new_name='Product',
        ),
    ]
