# Generated by Django 4.2.30 on 2026-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vechicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
